cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'antigen'
brew 'gnupg'
brew 'gpg-agent'
brew 'grc'
brew 'imagemagick'
brew 'jenv'
brew 'maven'
brew 'mongodb'
brew 'phantomjs'
brew 'pinentry-mac'
brew 'tree'

cask '1password'
cask 'alfred'
cask 'atext'
cask 'coconutbattery'
cask 'dash'
cask 'disk-inventory-x'
cask 'drop-to-gif'
cask 'dropbox'
cask 'dnscrypt'
cask 'geekbench'
cask 'gifrocket'
cask 'google-chrome'
cask 'grammarly'
cask 'imageoptim'
cask 'intellij-idea'
cask 'iterm2'
cask 'karabiner-elements'
cask 'paw'
cask 'querious'
cask 'robomongo'
cask 'ssh-tunnel-manager'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'sublime-text'
cask 'vagrant'
cask 'virtualbox'
cask 'viscosity'
